version: "3.8"

services:
  model-layer:
    container_name: running-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./container_output:/app/output"
    ports:
      - "4307:3000"
    depends_on:
      - db
    links:
      - db
  #    command: sleep 999999

  db:
    container_name: db
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      PUID: 502
      PGID: 20
      MYSQL_USER: sean
      MYSQL_PASSWORD: fahey # pragma: allowlist secret
      MYSQL_ROOT_PASSWORD: fahey # pragma: allowlist secret
      TZ: America/Los_Angeles
      BIND-ADDRESS: 0.0.0.0
    ports:
      - "4308:3306"
    volumes:
      - "./Docker/db-data:/config/databases"
    restart: always
